### PR TITLE
add package.json

### PR DESCRIPTION
**Pull request by caub**
I did a `npm init` and added rollup to make it importable as well as standalone (your L.Terminator.js is generated from it)
Could you publish `npm publish` to npm, if that package is working?

I picked the npm name `leaflet.terminator`, `leaflet-terminator` is taken, feel free to choose another name

### CODE REVIEW

**Comment by caub** [comment]
@joergdietrich do you think we can publish it on npm? I've tested it last days, it works well, even better than [`leaflet-terminator`](https://github.com/mapbox/leaflet-terminator) (the bounds are larger)

Only annoying thing is the path added has a 'leaflet-interactive' class

**Comment by joergdietrich** [comment]
Many thanks for your contribution, @caub ! I haven't had a chance to review it yet. Will do so later today or tomorow.

**Comment by caub** [comment]
Also you can just add index.html in the master branch, and in project settings you can use master as gh-pages, will be simpler

**Comment by caub** [comment]
Hi @joergdietrich 
I think the indents were not consistent, https://github.com/joergdietrich/Leaflet.Terminator/blob/master/L.Terminator.js#L28-L41 tabs in first method, spaces in second

So I've put full spaces https://github.com/caub/Leaflet.Terminator/blob/npm/index.js#L29-L42 do you prefer tabs? (I don't mind at all)

**Comment by caub** [comment]
@joergdietrich so?

**Comment by joergdietrich** [comment]
Many thanks again and my sincere apologies for the long time it took to me to get this merged!

**Comment by caub** [comment]
Could you change in Settings > Options > Github Pages > Source: master branch

so that https://joergdietrich.github.io/Leaflet.Terminator/demo also work

also https://joergdietrich.github.io/Leaflet.Terminator need fixes since L.Terminator.js is not committed in GH, need to use https://unpkg.com/@joergdietrich/leaflet.terminator@1.0.0/L.Terminator.js

ps: why did you change https://unpkg.com/leaflet.terminator to https://unpkg.com/@joergdietrich/leaflet.terminator/ (with scope)?

**Comment by joergdietrich** [comment]
Already working on it. Thanks!

The name change was necessary because npm now checks for packages with names that are too similar and won't allow them. It determined that leaflet.terminator was too close to leaflet-terminator and wouldn't accept the package.

**Comment by joergdietrich** [comment]
And done! Feel free to re-open or create a new issue if you spot anything. Thanks again.

**Pull request merged**
